### ISSUE TITLE
Mongodb-odb changed

### ISSUE THREAD

**Issue by alexgenovese** [lorenzo/MongoCake#4]
Hello Lorenzo, 
I think that mongodb_odm folder on github is changed. Can you change the path  in the bootstrap in order to fix it?

Thanks!
-A

**Comment by lorenzo** [comment]
What would be the proper fix?

**Comment by alexgenovese** [comment]
I don't know. I have downloaded the folder in mongodb_odm linked on github but it doesn't work because it show me a folder that doesn't exists in the path of mongodb_odm folder!

**Comment by lorenzo** [comment]
did you run git submodule update --init --recursive ?

**Comment by alexgenovese** [comment]
no.....
I'm sorry! :(

Thanks for your help!!
